"""Create table

Revision ID: 54070e6d52f1
Revises: 89878c720d00
Create Date: 2026-03-29 13:44:19.315838

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54070e6d52f1"
down_revision: Union[str, Sequence[str], None] = "89878c720d00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox", "attempts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outbox",
        sa.Column("attempts", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
