"""create tickets

Revision ID: 829c38d58f96
Revises: 4a0ac801ed40
Create Date: 2026-03-21 19:59:47.349782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829c38d58f96'
down_revision: Union[str, Sequence[str], None] = '4a0ac801ed40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_events_synced', sa.Integer(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_metadata')
    # ### end Alembic commands ###
