"""Create table

Revision ID: 9a31e3565df5
Revises: d0ab38707833
Create Date: 2026-03-30 11:12:08.108309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a31e3565df5'
down_revision: Union[str, Sequence[str], None] = 'd0ab38707833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotency_keys', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('idempotency_keys', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('idempotency_keys', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('idempotency_keys', 'seat',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idempotency_keys', 'seat',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('idempotency_keys', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('idempotency_keys', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('idempotency_keys', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
