"""Create table

Revision ID: d0ab38707833
Revises: 86f9311d6378
Create Date: 2026-03-30 10:40:07.589293

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0ab38707833"
down_revision: Union[str, Sequence[str], None] = "86f9311d6378"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "idempotency_keys", sa.Column("first_name", sa.String(), nullable=False)
    )
    op.add_column(
        "idempotency_keys", sa.Column("last_name", sa.String(), nullable=False)
    )
    op.add_column("idempotency_keys", sa.Column("email", sa.String(), nullable=False))
    op.add_column("idempotency_keys", sa.Column("seat", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("idempotency_keys", "seat")
    op.drop_column("idempotency_keys", "email")
    op.drop_column("idempotency_keys", "last_name")
    op.drop_column("idempotency_keys", "first_name")
    # ### end Alembic commands ###
